### ISSUE TITLE
Unable to compile mmEmptyExample

### ISSUE THREAD

**Issue by amitahire** [numediart/MotionMachine#3]
Hello, 

I have been trying to compile the mmEmptyExample project on Windows 8.1 and VS 2015
 but I get the following error : 

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(771): error C2988: unrecognizable template declaration/definition (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(771): error C2059: syntax error: 'const' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(771): error C2947: expecting '>' to terminate template-argument-list, found '<' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(771): error C2059: syntax error: '-' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(771): error C2059: syntax error: '+' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(771): error C2059: syntax error: ')' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(779): error C2649: 'typename': is not a 'class' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(801): error C2649: 'typename': is not a 'class' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(954): error C2059: syntax error: ')' (compiling source file src\ofApp.cpp)
3>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(954): fatal error C1075: the left angle-bracket '<' was unmatched at the end of the file (compiling source file src\ofApp.cpp)
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Any help would be appriciated! Thanks.

**Comment by celsius** [comment]
For the record, these errors are usually a sign that C++11 is not enabled in the project settings. Maybe take a look in that direction in you VS 2015 settings?

**Comment by amitahire** [comment]
Thanks for the reply, I have been looking into it but still I cant seem to make it compile. 

C++11 features are suppoerd to "active" by default in Visual Studio 2015, arent they? I cant seem to compile, I have tried adding all different compiler flags but to no avail ( preprocessor flags or CXX_Flags  such as _cplusplus)

Someone even suggested online to do the following, but to no avail 
`#if defined(_MSC_VER) && (_MSC_VER < 1800 || defined(__cplusplus))`
`#undef __cplusplus`
`#define __cplusplus 201103L`
`#endif`

Any other suggestions? 

Thanks.
> Microsoft Visual Studio Community 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
Installed Version: Community
Visual C++ 2015   00322-20000-00000-AA423
Microsoft Visual C++ 2015

**Comment by thiravet** [comment]
Hello

I think I have corrected your problem. I have pushed the solution on the master branch.
Sorry for the delay but i had to update my VS2015 to succeed in reproducing your bug.(chrono file has changed).

Thanks for reporting this issue

Thierry

**Comment by amitahire** [comment]
Thank you. It compiles now.
